dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk11

script:
  - ./gradlew check jacocoTestReport
  - curl -fLso codecov https://codecov.io/bash;
    VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
    ls -la;
    echo $VERSION;
